#spring.application.name=Ecommerce
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/msca
spring.datasource.username=root
spring.datasource.password=Weedyboy@9990

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Set a fixed username and password for local development
#spring.security.user.name=admin
#spring.security.user.password=pass@123

#jwt stuff
jwt.SECRETKEY=aGRnZmRnZmhkZ3Nmc2RkaGdkZmtzZGhma3VoaGZqaGprZmdoa2doa2psaGdoYmdraGJqaHNmbGFmamdhmZrGloaXB1ZmhmZ2l1ZnNrZGZzaGZqaw
jwt.tokenvalidity=9000000
