package com.MSCA.Ecommerce.enums;

public enum Role {

    ROLE_SUPER_ADMIN,
    ROLE_WAREHOUSE_ADMIN,
    ROLE_WAREHOUSE_MANAGER,
    ROLE_WAREHOUSE_SUPERVISOR,
    ROLE_WAREHOUSE_STAFF_HEAD,
    ROLE_WAREHOUSE_STAFF,
    ROLE_CUSTOMER
}
